[0m15:40:26.116210 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173A82A0F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173A778BD70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173A778AAB0>]}


============================== 15:40:26.120872 | f0626f2b-f3cc-4622-98f9-2abc4b6f9952 ==============================
[0m15:40:26.120872 [info ] [MainThread]: Running with dbt=1.10.4
[0m15:40:26.120872 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init my_dbt_project', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:40:26.135454 [debug] [MainThread]: Starter project path: C:\Users\George\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m15:40:26.152962 [info ] [MainThread]: 
Your new dbt project "my_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:40:26.152962 [info ] [MainThread]: Setting up your profile.
[0m15:40:40.511833 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m15:40:40.511833 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m15:40:40.511833 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m15:47:51.373776 [info ] [MainThread]: Profile my_dbt_project written to C:\Users\George\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:47:51.374774 [debug] [MainThread]: Command `dbt init` succeeded at 15:47:51.374774 after 445.36 seconds
[0m15:47:51.374774 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173A81AEBD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173CB223E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000173CAFF52B0>]}
[0m15:47:51.375772 [debug] [MainThread]: Flushing usage events
[0m15:47:52.363812 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:48:00.890775 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029003EEB890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000290040E7230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029003108740>]}


============================== 15:48:00.894922 | 6dd5120b-4074-481a-9e86-f08539cdd6d8 ==============================
[0m15:48:00.894922 [info ] [MainThread]: Running with dbt=1.10.4
[0m15:48:00.894922 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:48:00.894922 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:48:00.895942 [debug] [MainThread]: Command `dbt run` failed at 15:48:00.895942 after 0.12 seconds
[0m15:48:00.895942 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029004523D40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029001274EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000290042000B0>]}
[0m15:48:00.896931 [debug] [MainThread]: Flushing usage events
[0m15:48:01.865055 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:19:28.844335 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9ED822CF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9ED3EDCA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9ED8233B0>]}


============================== 19:19:28.848347 | a571373a-d026-4efb-aba1-bd3d009c9ea6 ==============================
[0m19:19:28.848347 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:19:28.848347 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'empty': 'None', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'log_format': 'default', 'quiet': 'False', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'invocation_command': 'dbt init', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'write_json': 'True', 'target_path': 'None'}
[0m19:19:35.915770 [debug] [MainThread]: Starter project path: C:\Users\George\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m19:19:35.935780 [info ] [MainThread]: 
Your new dbt project "dbt_demo" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:19:35.935780 [info ] [MainThread]: Setting up your profile.
[0m19:19:41.556859 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m19:19:41.556859 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m19:19:41.557892 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m19:20:48.986825 [info ] [MainThread]: Profile dbt_demo written to C:\Users\George\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m19:20:48.988277 [debug] [MainThread]: Command `dbt init` succeeded at 19:20:48.986825 after 80.28 seconds
[0m19:20:48.988277 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F991CE56A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F991A0B650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F991512CF0>]}
[0m19:20:48.988277 [debug] [MainThread]: Flushing usage events
[0m19:20:50.006436 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:21:05.896427 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026A1E5F8F20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026A1E733D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026A1E13E570>]}


============================== 19:21:05.900434 | cffbc9a1-11d9-44de-91f4-d03fc77570c3 ==============================
[0m19:21:05.900434 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:21:05.900434 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'empty': 'None', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'invocation_command': 'dbt debug', 'fail_fast': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'target_path': 'None', 'write_json': 'True'}
[0m19:21:05.916764 [info ] [MainThread]: dbt version: 1.10.4
[0m19:21:05.916764 [info ] [MainThread]: python version: 3.12.10
[0m19:21:05.917776 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m19:21:05.917776 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m19:21:06.609918 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m19:21:06.609918 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m19:21:06.609918 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m19:21:07.168547 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m19:21:07.169539 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m19:21:07.169539 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m19:21:07.170504 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m19:21:07.170504 [debug] [MainThread]: Command `dbt debug` failed at 19:21:07.170504 after 1.38 seconds
[0m19:21:07.170504 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026A1E087AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026A21925370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026A41D697C0>]}
[0m19:21:07.171838 [debug] [MainThread]: Flushing usage events
[0m19:21:08.193706 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:25:28.435413 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A9A28FE990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A9A28FF9B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A9A28FC5F0>]}


============================== 14:25:28.439575 | d1ad43e0-833a-4417-9b3d-abf310a2c010 ==============================
[0m14:25:28.439575 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:25:28.440580 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'write_json': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'log_format': 'default', 'quiet': 'False', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'invocation_command': 'dbt init', 'fail_fast': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'target_path': 'None'}
[0m14:25:44.855111 [debug] [MainThread]: Starter project path: C:\Users\George\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m14:25:44.876114 [info ] [MainThread]: 
Your new dbt project "dbt_eng" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:25:44.876114 [info ] [MainThread]: Setting up your profile.
[0m14:25:50.371506 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:25:50.371506 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:25:50.372499 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:27:09.268805 [info ] [MainThread]: Profile dbt_eng written to C:\Users\George\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:27:09.269804 [debug] [MainThread]: Command `dbt init` succeeded at 14:27:09.269804 after 100.96 seconds
[0m14:27:09.270803 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A9A2A223F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A9A2EDFE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A9C40F3410>]}
[0m14:27:09.270803 [debug] [MainThread]: Flushing usage events
[0m14:27:10.373538 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:27:18.809573 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021967AE7200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000219648A6270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021964E54BC0>]}


============================== 14:27:18.814580 | d400ab87-0386-427b-b01c-581275462497 ==============================
[0m14:27:18.814580 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:27:18.814580 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'write_json': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'no_print': 'None', 'fail_fast': 'False', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'target_path': 'None', 'use_experimental_parser': 'False'}
[0m14:27:18.841672 [info ] [MainThread]: dbt version: 1.10.4
[0m14:27:18.842910 [info ] [MainThread]: python version: 3.12.10
[0m14:27:18.842910 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m14:27:18.842910 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m14:27:19.550506 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:27:19.551442 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:27:19.551442 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:27:20.117162 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m14:27:20.118164 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m14:27:20.118164 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m14:27:20.119226 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:27:20.119226 [debug] [MainThread]: Command `dbt debug` failed at 14:27:20.119226 after 1.42 seconds
[0m14:27:20.120283 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000219670E97F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002196A7B66C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002190BE32180>]}
[0m14:27:20.120283 [debug] [MainThread]: Flushing usage events
[0m14:27:21.086025 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:28:15.151603 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A9A8F8860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A9AF1E480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A97E92210>]}


============================== 14:28:15.155610 | 41358ae1-a9dd-46f8-8625-690235a466e3 ==============================
[0m14:28:15.155610 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:28:15.156609 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'log_format': 'default', 'quiet': 'False', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'invocation_command': 'dbt debug', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'target_path': 'None', 'write_json': 'True'}
[0m14:28:15.170122 [info ] [MainThread]: dbt version: 1.10.4
[0m14:28:15.171122 [info ] [MainThread]: python version: 3.12.10
[0m14:28:15.171122 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m14:28:15.172122 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m14:28:15.893877 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:28:15.893877 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:28:15.894877 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:28:16.440914 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m14:28:16.441913 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m14:28:16.442910 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m14:28:16.442910 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:28:16.443947 [debug] [MainThread]: Command `dbt debug` failed at 14:28:16.443947 after 1.41 seconds
[0m14:28:16.443947 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020A9AD997F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020ABD6B2660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020ABDE28950>]}
[0m14:28:16.444955 [debug] [MainThread]: Flushing usage events
[0m14:28:18.152452 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:29:02.252089 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026510EA66C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026510721CA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026510722390>]}


============================== 14:29:02.256093 | 6718a79b-0f87-4c6b-a724-7e2ba686e4fc ==============================
[0m14:29:02.256093 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:29:02.257097 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'write_json': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'empty': 'None', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'log_format': 'default', 'quiet': 'False', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'invocation_command': 'dbt debug', 'fail_fast': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'target_path': 'None'}
[0m14:29:02.272502 [info ] [MainThread]: dbt version: 1.10.4
[0m14:29:02.272502 [info ] [MainThread]: python version: 3.12.10
[0m14:29:02.272502 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m14:29:02.273501 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m14:29:03.000991 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:29:03.000991 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:29:03.002145 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:29:03.551186 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m14:29:03.553177 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m14:29:03.554170 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m14:29:03.555176 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:29:03.556172 [debug] [MainThread]: Command `dbt debug` failed at 14:29:03.556172 after 1.43 seconds
[0m14:29:03.557232 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002650E5C2210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002651184F110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026532A05460>]}
[0m14:29:03.557232 [debug] [MainThread]: Flushing usage events
[0m14:29:04.515799 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:30:08.184153 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2BD753110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2BA512360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2BCC8F5F0>]}


============================== 14:30:08.188403 | e3964a54-02f7-4d5f-a9e5-ddfd419023de ==============================
[0m14:30:08.188403 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:30:08.189403 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'invocation_command': 'dbt debug', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'target_path': 'None', 'write_json': 'True'}
[0m14:30:08.208513 [info ] [MainThread]: dbt version: 1.10.4
[0m14:30:08.208513 [info ] [MainThread]: python version: 3.12.10
[0m14:30:08.209858 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m14:30:08.209858 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m14:30:08.904958 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:30:08.904958 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:30:08.904958 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:30:09.470293 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m14:30:09.470293 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m14:30:09.471241 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m14:30:09.471241 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:30:09.473541 [debug] [MainThread]: Command `dbt debug` failed at 14:30:09.473541 after 1.41 seconds
[0m14:30:09.473541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2BAFF25A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2E00DB9B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2E0848CB0>]}
[0m14:30:09.473541 [debug] [MainThread]: Flushing usage events
[0m14:30:10.534967 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:31:20.318209 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022797D123F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227947D2210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022797D10590>]}


============================== 14:31:20.322207 | 286fb156-96ce-428a-a061-44479ad6a67c ==============================
[0m14:31:20.322207 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:31:20.322207 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'write_json': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'True', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'log_format': 'default', 'quiet': 'False', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'no_print': 'None', 'invocation_command': 'dbt parse --debug', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'target_path': 'None'}
[0m14:31:20.323208 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:31:20.324207 [debug] [MainThread]: Command `dbt parse` failed at 14:31:20.324207 after 0.11 seconds
[0m14:31:20.324207 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227976638C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227975E7320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022797BF6360>]}
[0m14:31:20.325208 [debug] [MainThread]: Flushing usage events
[0m14:31:21.346200 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:34:32.215343 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228658D39E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022862C06330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228637D3F80>]}


============================== 14:34:32.219945 | a02cb567-2f96-4c24-82f9-b42babc5997c ==============================
[0m14:34:32.219945 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:34:32.219945 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'write_json': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'True', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'invocation_command': 'dbt parse --debug', 'fail_fast': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'target_path': 'None', 'use_experimental_parser': 'False'}
[0m14:34:32.220944 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:34:32.220944 [debug] [MainThread]: Command `dbt parse` failed at 14:34:32.220944 after 0.13 seconds
[0m14:34:32.221945 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228658D39E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022866F01220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228656AE840>]}
[0m14:34:32.221945 [debug] [MainThread]: Flushing usage events
[0m14:34:34.098537 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:34:39.872947 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C93294E960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C9306F6210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C9330CFBC0>]}


============================== 14:34:39.877958 | 661d0bad-95b6-4eaf-8138-1583b1d2aae1 ==============================
[0m14:34:39.877958 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:34:39.877958 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'target_path': 'None', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'no_print': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'write_json': 'True'}
[0m14:34:39.894302 [info ] [MainThread]: dbt version: 1.10.4
[0m14:34:39.895301 [info ] [MainThread]: python version: 3.12.10
[0m14:34:39.896399 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m14:34:39.896399 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m14:34:40.598990 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:34:40.599992 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:34:40.599992 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:34:41.136305 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m14:34:41.137306 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m14:34:41.137306 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m14:34:41.138288 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:34:41.139277 [debug] [MainThread]: Command `dbt debug` failed at 14:34:41.139277 after 1.39 seconds
[0m14:34:41.139277 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C9336DE270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C9568D03E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C956A9BF80>]}
[0m14:34:41.140406 [debug] [MainThread]: Flushing usage events
[0m14:34:42.082598 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:38:57.026785 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002464E0E6CC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002464E8B21B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002464E5E0B00>]}


============================== 14:38:57.031169 | 3afcf8e2-784b-419f-88fb-4bb4787f011f ==============================
[0m14:38:57.031169 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:38:57.032133 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'empty': 'None', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'no_print': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'write_json': 'True', 'target_path': 'None'}
[0m14:38:57.047225 [info ] [MainThread]: dbt version: 1.10.4
[0m14:38:57.048549 [info ] [MainThread]: python version: 3.12.10
[0m14:38:57.048549 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m14:38:57.048549 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m14:38:57.780764 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:38:57.780764 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:38:57.781765 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:38:58.317169 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m14:38:58.318161 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m14:38:58.318161 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m14:38:58.319156 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:38:58.319156 [debug] [MainThread]: Command `dbt debug` failed at 14:38:58.319156 after 1.43 seconds
[0m14:38:58.320632 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002464E0E6CC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002466FEF03E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002466FE76C60>]}
[0m14:38:58.320632 [debug] [MainThread]: Flushing usage events
[0m14:38:59.498635 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:39:52.140396 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019B2B282720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019B2B453C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019B28542120>]}


============================== 14:39:52.144024 | 5713aa19-6093-49cb-9ffd-c6562fb55b6c ==============================
[0m14:39:52.144024 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:39:52.145027 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'target_path': 'None', 'cache_selected_only': 'False', 'warn_error': 'None', 'empty': 'None', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'log_format': 'default', 'quiet': 'False', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'no_print': 'None', 'fail_fast': 'False', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'write_json': 'True', 'use_experimental_parser': 'False'}
[0m14:40:00.987465 [debug] [MainThread]: Starter project path: C:\Users\George\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m14:40:01.002101 [info ] [MainThread]: 
Your new dbt project "dbt_eng" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:40:01.002101 [info ] [MainThread]: Setting up your profile.
[0m14:40:03.330887 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m14:40:03.330887 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m14:40:03.331886 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m14:41:35.036982 [info ] [MainThread]: Profile dbt_eng written to C:\Users\George\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:41:35.038200 [debug] [MainThread]: Command `dbt init` succeeded at 14:41:35.038200 after 103.01 seconds
[0m14:41:35.038200 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019B2C897EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019B4E8978F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019B4E189BB0>]}
[0m14:41:35.039201 [debug] [MainThread]: Flushing usage events
[0m14:41:36.221112 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:41:43.198040 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024539B674A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000245375021B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024539F81640>]}


============================== 14:41:43.202352 | 16785bcb-95c6-4328-a2b1-b0c49717eae7 ==============================
[0m14:41:43.202352 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:41:43.202352 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'empty': 'None', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'invocation_command': 'dbt init', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'write_json': 'True', 'target_path': 'None'}
[0m19:44:24.137418 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1DC5D98B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1DB876930>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1DC410710>]}


============================== 19:44:24.143417 | 2de29a30-554b-4677-966a-49b2e06e3e6f ==============================
[0m19:44:24.143417 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:44:24.144417 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'empty': 'None', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'invocation_command': 'dbt init', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'write_json': 'True', 'target_path': 'None'}
[0m19:44:58.270752 [debug] [MainThread]: Starter project path: C:\Users\George\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m19:44:58.304507 [info ] [MainThread]: 
Your new dbt project "jra_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:44:58.305904 [info ] [MainThread]: Setting up your profile.
[0m19:45:03.732927 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m19:45:03.734100 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m19:45:03.734100 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m19:50:26.824842 [info ] [MainThread]: Profile jra_dbt written to C:\Users\George\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m19:50:26.897329 [debug] [MainThread]: Command `dbt init` succeeded at 19:50:26.894200 after 362.93 seconds
[0m19:50:26.905225 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1FF92BDA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1DF6ED3A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1FDBF9160>]}
[0m19:50:26.911663 [debug] [MainThread]: Flushing usage events
[0m19:50:28.001833 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:50:39.136479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000123FB7F26C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000123FB1177A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000123FB114AA0>]}


============================== 19:50:39.141452 | 3fa3a6d1-1eed-47cf-884a-d3b1981a9df6 ==============================
[0m19:50:39.141452 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:50:39.142462 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'invocation_command': 'dbt debug', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'write_json': 'True', 'target_path': 'None'}
[0m19:50:39.171951 [info ] [MainThread]: dbt version: 1.10.4
[0m19:50:39.172950 [info ] [MainThread]: python version: 3.12.10
[0m19:50:39.172950 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m19:50:39.173952 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m19:50:39.970978 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m19:50:39.970978 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m19:50:39.970978 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m19:50:40.900135 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m19:50:40.901102 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m19:50:40.901102 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m19:50:40.902101 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m19:50:40.902101 [debug] [MainThread]: Command `dbt debug` failed at 19:50:40.902101 after 1.97 seconds
[0m19:50:40.903373 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000123FBC61460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000123FE950380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000123FFC55430>]}
[0m19:50:40.903877 [debug] [MainThread]: Flushing usage events
[0m19:50:41.870442 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:52:52.559958 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257507E2F00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257507E39B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257507E30E0>]}


============================== 19:52:52.565497 | 5aa526f6-1784-400a-8466-7463aab2ab04 ==============================
[0m19:52:52.565497 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:52:52.566501 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'log_format': 'default', 'quiet': 'False', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'no_print': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'write_json': 'True', 'target_path': 'None'}
[0m19:52:52.590378 [info ] [MainThread]: dbt version: 1.10.4
[0m19:52:52.591456 [info ] [MainThread]: python version: 3.12.10
[0m19:52:52.591456 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m19:52:52.592567 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m19:52:53.471027 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m19:52:53.471027 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m19:52:53.471027 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m19:52:54.439466 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m19:52:54.439466 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m19:52:54.440439 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m19:52:54.440439 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m19:52:54.441454 [debug] [MainThread]: Command `dbt debug` failed at 19:52:54.441454 after 2.07 seconds
[0m19:52:54.441454 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002575082C980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257530E13D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000257738C6C60>]}
[0m19:52:54.442453 [debug] [MainThread]: Flushing usage events
[0m19:52:55.728254 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:54:22.906435 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EA1D2B14F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EA1D2B2E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EA1D2B39E0>]}


============================== 19:54:22.911788 | db3d0a48-8b38-4013-943e-67ee94db4030 ==============================
[0m19:54:22.911788 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:54:22.913165 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'target_path': 'None', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': 'C:\\Users\\George\\.dbt', 'debug': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'empty': 'None', 'quiet': 'False', 'log_format': 'default', 'use_colors': 'True', 'partial_parse': 'True', 'version_check': 'True', 'log_path': 'logs', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'fail_fast': 'False', 'no_print': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'write_json': 'True', 'use_experimental_parser': 'False'}
[0m19:54:22.935254 [info ] [MainThread]: dbt version: 1.10.4
[0m19:54:22.935254 [info ] [MainThread]: python version: 3.12.10
[0m19:54:22.936321 [info ] [MainThread]: python path: C:\Users\George\AppData\Local\Programs\Python\Python312\python.exe
[0m19:54:22.936321 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m19:54:23.694693 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m19:54:23.696106 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m19:54:23.696106 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m19:54:24.609459 [info ] [MainThread]: Using profiles dir at C:\Users\George\.dbt
[0m19:54:24.610410 [info ] [MainThread]: Using profiles.yml file at C:\Users\George\.dbt\profiles.yml
[0m19:54:24.610410 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\George\Desktop\JR AI engineer\JRDE16-JLA\dbt_project.yml
[0m19:54:24.611399 [info ] [MainThread]: adapter type: databricks
[0m19:54:24.611399 [info ] [MainThread]: adapter version: 1.10.4
[0m19:54:24.612574 [info ] [MainThread]: Configuration:
[0m19:54:24.612574 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m19:54:24.612574 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m19:54:24.613692 [info ] [MainThread]: Required dependencies:
[0m19:54:24.613692 [debug] [MainThread]: Executing "git --help"
[0m19:54:24.644210 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m19:54:24.644210 [debug] [MainThread]: STDERR: "b''"
[0m19:54:24.644210 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m19:54:24.645583 [info ] [MainThread]: Connection:
[0m19:54:24.645583 [info ] [MainThread]:   host: https://dbc-e8afd837-2b61.cloud.databricks.com
[0m19:54:24.645583 [info ] [MainThread]:   http_path: https://dbc-e8afd837-2b61.cloud.databricks.com
[0m19:54:24.646703 [info ] [MainThread]:   catalog: jra
[0m19:54:24.646703 [info ] [MainThread]:   schema: initial
[0m19:54:24.646703 [info ] [MainThread]: Registered adapter: databricks=1.10.4
[0m19:54:25.075167 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(session-id=None, name=debug, idle-time=0s, language=None, compute-name=) - Creating connection
[0m19:54:25.076129 [debug] [MainThread]: Acquiring new databricks connection 'debug'
[0m19:54:25.076129 [debug] [MainThread]: Using databricks connection "debug"
[0m19:54:25.076129 [debug] [MainThread]: On debug: select 1 as id
[0m19:54:25.076129 [debug] [MainThread]: Opening a new connection, currently in state init
